version: '3'
services:
  api-gateway:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AUTH_API_URL=http://192.168.1.181:8001
      - ROOMS_API_URL=http://192.168.1.181:8002
      - CHAT_API_URL=http://192.168.1.181:8003
      - JWT_SECRET=tu_secreto_super_seguro