version: '3'

services:
  rooms-api:
    build: .
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGODB_URI=mongodb://192.168.1.181:27018/rooms_service
      - JWT_SECRET=tu_secreto_super_seguro
      - API_AUTH_URL=http://192.168.1.181:3001
      - API_CHAT_URL=http://192.168.1.181:3003
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017" # Mongo expuesto en el puerto 27018
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
