version: '3'
services:
  chat-api:
    build: .
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONGODB_URI=mongodb://192.168.1.181:27019,192.168.1.181:27029,192.168.1.181:27039/chat_service?replicaSet=rs_chat
      - JWT_SECRET=tu_secreto_super_seguro
      - API_AUTH_URL=http://192.168.1.181:8001
      - API_ROOMS_URL=http://192.168.1.181:8002
      - SERVICE_TOKEN=token_servicio_para_comunicacion_interna

  mongo1:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongo-data1:/data/db
    command: mongod --replSet rs_chat --port 27017 --bind_ip 0.0.0.0

  mongo2:
    image: mongo:latest
    ports:
      - "27029:27017"
    volumes:
      - mongo-data2:/data/db
    command: mongod --replSet rs_chat --port 27017 --bind_ip 0.0.0.0

  mongo3:
    image: mongo:latest
    ports:
      - "27039:27017"
    volumes:
      - mongo-data3:/data/db
    command: mongod --replSet rs_chat --port 27017 --bind_ip 0.0.0.0

volumes:
  mongo-data1:
  mongo-data2:
  mongo-data3: